# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'PracticeRx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PracticeRx
pod 'RxSwift', '6.5.0'
pod 'RxCocoa', '6.5.0'

  target 'PracticeRxTests' do
    inherit! :search_paths
    # Pods for testing
pod 'RxBlocking', '6.5.0'
pod 'RxTest', '6.5.0'
  end

  target 'PracticeRxUITests' do
    # Pods for testing
  end

end
