# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'GoodList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoodList
pod 'RxSwift', '6.5.0'
pod 'RxCocoa', '6.5.0'
pod 'SnapKit', '5.6.0'

  target 'GoodListTests' do
    inherit! :search_paths
    # Pods for testing
pod 'RxBlocking', '6.5.0'
pod 'RxTest', '6.5.0'
  end

  target 'GoodListUITests' do
    # Pods for testing
  end

end
